// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/models/shared"
	"net/http"
)

type DeletePolicyRequest struct {
	// policy name
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
}

func (o *DeletePolicyRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

type DeletePolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PoliciesV1PolicyDeleteResponse *shared.PoliciesV1PolicyDeleteResponse
	// Not Found
	MetaV1ErrorResponse *shared.MetaV1ErrorResponse
}

func (o *DeletePolicyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeletePolicyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeletePolicyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeletePolicyResponse) GetPoliciesV1PolicyDeleteResponse() *shared.PoliciesV1PolicyDeleteResponse {
	if o == nil {
		return nil
	}
	return o.PoliciesV1PolicyDeleteResponse
}

func (o *DeletePolicyResponse) GetMetaV1ErrorResponse() *shared.MetaV1ErrorResponse {
	if o == nil {
		return nil
	}
	return o.MetaV1ErrorResponse
}
