// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/models/shared"
	"net/http"
)

type DeleteStackRequest struct {
	// stack id
	Stack string `pathParam:"style=simple,explode=false,name=stack"`
}

func (o *DeleteStackRequest) GetStack() string {
	if o == nil {
		return ""
	}
	return o.Stack
}

type DeleteStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	StacksV1StacksDeleteResponse *shared.StacksV1StacksDeleteResponse
	// Not Found
	MetaV1ErrorResponse *shared.MetaV1ErrorResponse
}

func (o *DeleteStackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteStackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteStackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteStackResponse) GetStacksV1StacksDeleteResponse() *shared.StacksV1StacksDeleteResponse {
	if o == nil {
		return nil
	}
	return o.StacksV1StacksDeleteResponse
}

func (o *DeleteStackResponse) GetMetaV1ErrorResponse() *shared.MetaV1ErrorResponse {
	if o == nil {
		return nil
	}
	return o.MetaV1ErrorResponse
}
