// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/models/shared"
	"net/http"
)

type DeleteSystemRequest struct {
	// system ID
	System string `pathParam:"style=simple,explode=false,name=system"`
	// if set to 'false', only deletes the system configuration and does not delete associated objects
	Recursive *string `queryParam:"style=form,explode=true,name=recursive"`
}

func (o *DeleteSystemRequest) GetSystem() string {
	if o == nil {
		return ""
	}
	return o.System
}

func (o *DeleteSystemRequest) GetRecursive() *string {
	if o == nil {
		return nil
	}
	return o.Recursive
}

type DeleteSystemResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SystemsV1SystemsDeleteResponse *shared.SystemsV1SystemsDeleteResponse
	// Not Found
	MetaV1ErrorResponse *shared.MetaV1ErrorResponse
}

func (o *DeleteSystemResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteSystemResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteSystemResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteSystemResponse) GetSystemsV1SystemsDeleteResponse() *shared.SystemsV1SystemsDeleteResponse {
	if o == nil {
		return nil
	}
	return o.SystemsV1SystemsDeleteResponse
}

func (o *DeleteSystemResponse) GetMetaV1ErrorResponse() *shared.MetaV1ErrorResponse {
	if o == nil {
		return nil
	}
	return o.MetaV1ErrorResponse
}
