// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/Styra/terraform-provider-styra/internal/sdk/models/shared"
	"net/http"
)

type GetSecretRequest struct {
	// secret ID
	SecretID string `pathParam:"style=simple,explode=false,name=secretId"`
}

func (o *GetSecretRequest) GetSecretID() string {
	if o == nil {
		return ""
	}
	return o.SecretID
}

type GetSecretResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SecretsV1SecretsGetResponse *shared.SecretsV1SecretsGetResponse
	// Not Found
	MetaV1ErrorResponse *shared.MetaV1ErrorResponse
}

func (o *GetSecretResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSecretResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSecretResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSecretResponse) GetSecretsV1SecretsGetResponse() *shared.SecretsV1SecretsGetResponse {
	if o == nil {
		return nil
	}
	return o.SecretsV1SecretsGetResponse
}

func (o *GetSecretResponse) GetMetaV1ErrorResponse() *shared.MetaV1ErrorResponse {
	if o == nil {
		return nil
	}
	return o.MetaV1ErrorResponse
}
