// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/models/shared"
	"net/http"
)

type UpdateStackRequest struct {
	// stack id
	ID                       string                          `pathParam:"style=simple,explode=false,name=stack"`
	StacksV1StacksPutRequest shared.StacksV1StacksPutRequest `request:"mediaType=application/json"`
}

func (o *UpdateStackRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateStackRequest) GetStacksV1StacksPutRequest() shared.StacksV1StacksPutRequest {
	if o == nil {
		return shared.StacksV1StacksPutRequest{}
	}
	return o.StacksV1StacksPutRequest
}

type UpdateStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	StacksV1StacksPutResponse *shared.StacksV1StacksPutResponse
}

func (o *UpdateStackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateStackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateStackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateStackResponse) GetStacksV1StacksPutResponse() *shared.StacksV1StacksPutResponse {
	if o == nil {
		return nil
	}
	return o.StacksV1StacksPutResponse
}
