// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type AuthzV2ClaimConfig struct {
	// identity provider ID
	IdentityProvider *string `json:"identity_provider,omitempty"`
	// OIDC claim key
	Key string `json:"key"`
	// OIDC claim value. Use '*' to specify any value.
	Value string `json:"value"`
}

func (o *AuthzV2ClaimConfig) GetIdentityProvider() *string {
	if o == nil {
		return nil
	}
	return o.IdentityProvider
}

func (o *AuthzV2ClaimConfig) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *AuthzV2ClaimConfig) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
