// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AuthzV2Subject struct {
	ClaimConfig *AuthzV2ClaimConfig `json:"claim_config,omitempty"`
	// subject ID (not needed for claim subjects)
	ID *string `json:"id,omitempty"`
	// subject type e.g., user
	Kind string `json:"kind"`
}

func (o *AuthzV2Subject) GetClaimConfig() *AuthzV2ClaimConfig {
	if o == nil {
		return nil
	}
	return o.ClaimConfig
}

func (o *AuthzV2Subject) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AuthzV2Subject) GetKind() string {
	if o == nil {
		return ""
	}
	return o.Kind
}
