// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type AuthzV2RoleBindingsGetResponse struct {
	RequestID   *string                  `json:"request_id,omitempty"`
	Rolebinding AuthzV2RoleBindingConfig `json:"rolebinding"`
}

func (o *AuthzV2RoleBindingsGetResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AuthzV2RoleBindingsGetResponse) GetRolebinding() AuthzV2RoleBindingConfig {
	if o == nil {
		return AuthzV2RoleBindingConfig{}
	}
	return o.Rolebinding
}
