// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CryptoSignature struct {
	Excluded   interface{} `json:"excluded,omitempty"`
	Signatures interface{} `json:"signatures,omitempty"`
}

func (o *CryptoSignature) GetExcluded() interface{} {
	if o == nil {
		return nil
	}
	return o.Excluded
}

func (o *CryptoSignature) GetSignatures() interface{} {
	if o == nil {
		return nil
	}
	return o.Signatures
}
