// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type KeysConfig struct {
	Algorithm  string `json:"algorithm"`
	Key        string `json:"key"`
	PrivateKey string `json:"private_key"`
	Scope      string `json:"scope"`
}

func (o *KeysConfig) GetAlgorithm() string {
	if o == nil {
		return ""
	}
	return o.Algorithm
}

func (o *KeysConfig) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *KeysConfig) GetPrivateKey() string {
	if o == nil {
		return ""
	}
	return o.PrivateKey
}

func (o *KeysConfig) GetScope() string {
	if o == nil {
		return ""
	}
	return o.Scope
}
