// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LibrariesV1CreateLibraryRequest struct {
	Description   string                          `json:"description"`
	ReadOnly      bool                            `json:"read_only"`
	SourceControl *LibrariesV1SourceControlConfig `json:"source_control,omitempty"`
}

func (o *LibrariesV1CreateLibraryRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *LibrariesV1CreateLibraryRequest) GetReadOnly() bool {
	if o == nil {
		return false
	}
	return o.ReadOnly
}

func (o *LibrariesV1CreateLibraryRequest) GetSourceControl() *LibrariesV1SourceControlConfig {
	if o == nil {
		return nil
	}
	return o.SourceControl
}
