// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type LibrariesV1SystemBundle struct {
	BundleID string `json:"bundle_id"`
	Version  int64  `json:"version"`
}

func (o *LibrariesV1SystemBundle) GetBundleID() string {
	if o == nil {
		return ""
	}
	return o.BundleID
}

func (o *LibrariesV1SystemBundle) GetVersion() int64 {
	if o == nil {
		return 0
	}
	return o.Version
}
