// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type LibrariesV1SystemUsingLibrary struct {
	Bundles  []LibrariesV1SystemBundle `json:"bundles,omitempty"`
	SystemID string                    `json:"system_id"`
}

func (o *LibrariesV1SystemUsingLibrary) GetBundles() []LibrariesV1SystemBundle {
	if o == nil {
		return nil
	}
	return o.Bundles
}

func (o *LibrariesV1SystemUsingLibrary) GetSystemID() string {
	if o == nil {
		return ""
	}
	return o.SystemID
}
