// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type LibrariesV1LibraryResponse struct {
	Result LibrariesV1LibraryEntityExpanded `json:"result"`
}

func (o *LibrariesV1LibraryResponse) GetResult() LibrariesV1LibraryEntityExpanded {
	if o == nil {
		return LibrariesV1LibraryEntityExpanded{}
	}
	return o.Result
}
