// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/internal/utils"
	"time"
)

type MetaV2ObjectMeta struct {
	CreatedAt           *time.Time `json:"created_at,omitempty"`
	CreatedBy           *string    `json:"created_by,omitempty"`
	CreatedThrough      *string    `json:"created_through,omitempty"`
	LastModifiedAt      *time.Time `json:"last_modified_at,omitempty"`
	LastModifiedBy      *string    `json:"last_modified_by,omitempty"`
	LastModifiedThrough *string    `json:"last_modified_through,omitempty"`
}

func (m MetaV2ObjectMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MetaV2ObjectMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MetaV2ObjectMeta) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *MetaV2ObjectMeta) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *MetaV2ObjectMeta) GetCreatedThrough() *string {
	if o == nil {
		return nil
	}
	return o.CreatedThrough
}

func (o *MetaV2ObjectMeta) GetLastModifiedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastModifiedAt
}

func (o *MetaV2ObjectMeta) GetLastModifiedBy() *string {
	if o == nil {
		return nil
	}
	return o.LastModifiedBy
}

func (o *MetaV2ObjectMeta) GetLastModifiedThrough() *string {
	if o == nil {
		return nil
	}
	return o.LastModifiedThrough
}
