// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type MetaV1ErrorResponse struct {
	Code      string   `json:"code"`
	Errors    []string `json:"errors,omitempty"`
	Message   string   `json:"message"`
	RequestID *string  `json:"request_id,omitempty"`
}

func (o *MetaV1ErrorResponse) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *MetaV1ErrorResponse) GetErrors() []string {
	if o == nil {
		return nil
	}
	return o.Errors
}

func (o *MetaV1ErrorResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *MetaV1ErrorResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
