// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type PoliciesV1PoliciesPutRequest struct {
	// module file name to rego (and also data.json/data.yaml if enabled for the tenant) contents dictionary
	Modules   map[string]string `json:"modules"`
	Signature *CryptoSignature  `json:"signature,omitempty"`
}

func (o *PoliciesV1PoliciesPutRequest) GetModules() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Modules
}

func (o *PoliciesV1PoliciesPutRequest) GetSignature() *CryptoSignature {
	if o == nil {
		return nil
	}
	return o.Signature
}
