// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PoliciesV1PolicyGetResponse struct {
	RequestID *string     `json:"request_id,omitempty"`
	Result    interface{} `json:"result"`
}

func (o *PoliciesV1PolicyGetResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *PoliciesV1PolicyGetResponse) GetResult() interface{} {
	if o == nil {
		return nil
	}
	return o.Result
}
