// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type SecretsV1Secret struct {
	Description string           `json:"description"`
	ID          string           `json:"id"`
	Metadata    MetaV1ObjectMeta `json:"metadata"`
	Name        string           `json:"name"`
}

func (o *SecretsV1Secret) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *SecretsV1Secret) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SecretsV1Secret) GetMetadata() MetaV1ObjectMeta {
	if o == nil {
		return MetaV1ObjectMeta{}
	}
	return o.Metadata
}

func (o *SecretsV1Secret) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
