// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SecretsV1SecretsPutResponse struct {
	RequestID *string `json:"request_id,omitempty"`
}

func (o *SecretsV1SecretsPutResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
