// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SecretsV1SecretsDeleteResponse struct {
	RequestID *string `json:"request_id,omitempty"`
}

func (o *SecretsV1SecretsDeleteResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
