// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SecretsV1SecretsPutRequest struct {
	Description string `json:"description"`
	Name        string `json:"name"`
	Secret      string `json:"secret"`
}

func (o *SecretsV1SecretsPutRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *SecretsV1SecretsPutRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SecretsV1SecretsPutRequest) GetSecret() string {
	if o == nil {
		return ""
	}
	return o.Secret
}
