// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// TypeParameters - stack type parameter values (for template.* types)
type TypeParameters struct {
}

type StacksV1StacksPostRequest struct {
	Description   string                       `json:"description"`
	Name          string                       `json:"name"`
	ReadOnly      bool                         `json:"read_only"`
	SourceControl *StacksV1SourceControlConfig `json:"source_control,omitempty"`
	Type          string                       `json:"type"`
	// stack type parameter values (for template.* types)
	TypeParameters *TypeParameters `json:"type_parameters,omitempty"`
}

func (o *StacksV1StacksPostRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *StacksV1StacksPostRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *StacksV1StacksPostRequest) GetReadOnly() bool {
	if o == nil {
		return false
	}
	return o.ReadOnly
}

func (o *StacksV1StacksPostRequest) GetSourceControl() *StacksV1SourceControlConfig {
	if o == nil {
		return nil
	}
	return o.SourceControl
}

func (o *StacksV1StacksPostRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *StacksV1StacksPostRequest) GetTypeParameters() *TypeParameters {
	if o == nil {
		return nil
	}
	return o.TypeParameters
}
