// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// StacksV1StacksPutRequestTypeParameters - stack type parameter values (for template.* types)
type StacksV1StacksPutRequestTypeParameters struct {
}

type StacksV1StacksPutRequest struct {
	Description   string                       `json:"description"`
	Name          string                       `json:"name"`
	ReadOnly      bool                         `json:"read_only"`
	SourceControl *StacksV1SourceControlConfig `json:"source_control,omitempty"`
	Type          string                       `json:"type"`
	// stack type parameter values (for template.* types)
	TypeParameters *StacksV1StacksPutRequestTypeParameters `json:"type_parameters,omitempty"`
}

func (o *StacksV1StacksPutRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *StacksV1StacksPutRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *StacksV1StacksPutRequest) GetReadOnly() bool {
	if o == nil {
		return false
	}
	return o.ReadOnly
}

func (o *StacksV1StacksPutRequest) GetSourceControl() *StacksV1SourceControlConfig {
	if o == nil {
		return nil
	}
	return o.SourceControl
}

func (o *StacksV1StacksPutRequest) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

func (o *StacksV1StacksPutRequest) GetTypeParameters() *StacksV1StacksPutRequestTypeParameters {
	if o == nil {
		return nil
	}
	return o.TypeParameters
}
