// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type StacksV1SourceControlConfig struct {
	StackOrigin          *GitV1GitRepoConfig `json:"stack_origin,omitempty"`
	UseWorkspaceSettings bool                `json:"use_workspace_settings"`
}

func (o *StacksV1SourceControlConfig) GetStackOrigin() *GitV1GitRepoConfig {
	if o == nil {
		return nil
	}
	return o.StackOrigin
}

func (o *StacksV1SourceControlConfig) GetUseWorkspaceSettings() bool {
	if o == nil {
		return false
	}
	return o.UseWorkspaceSettings
}
