// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type StacksV1StacksDeleteResponse struct {
	RequestID *string `json:"request_id,omitempty"`
}

func (o *StacksV1StacksDeleteResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
