// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type StacksV1StacksPostResponse struct {
	Result StacksV1StackConfig `json:"result"`
}

func (o *StacksV1StacksPostResponse) GetResult() StacksV1StackConfig {
	if o == nil {
		return StacksV1StackConfig{}
	}
	return o.Result
}
