// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type SystemsV1AgentErrors struct {
	// list of system errors
	Errors []MetaV1Status `json:"errors"`
	// true if the the system is waiting for error to be resolved
	Waiting bool `json:"waiting"`
}

func (o *SystemsV1AgentErrors) GetErrors() []MetaV1Status {
	if o == nil {
		return []MetaV1Status{}
	}
	return o.Errors
}

func (o *SystemsV1AgentErrors) GetWaiting() bool {
	if o == nil {
		return false
	}
	return o.Waiting
}
