// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/internal/utils"
)

type SystemsV1BundleDistributionS3Config struct {
	// access key id and secret access key are looked under the key <name>/<access_keys>
	AccessKeys *string `json:"access_keys,omitempty"`
	// bucket name
	Bucket string `json:"bucket"`
	// context bundle path. The name must not use template variables
	ContextPath *string `default:"context-{policy_path}" json:"context_path"`
	// discovery bundle path. Template variables can be used in the name
	DiscoveryPath *string `default:"discovery.tgz" json:"discovery_path"`
	// AWS endpoint
	Endpoint       *string                                            `json:"endpoint,omitempty"`
	OpaCredentials *SystemsV1BundleDistributionS3ConfigOpaCredentials `json:"opa_credentials,omitempty"`
	// policy bundle path. Template variables can be used in the name
	PolicyPath *string `default:"bundle.tgz" json:"policy_path"`
	// AWS region
	Region string `json:"region"`
	// AWS role
	RoleArn *string `json:"role_arn,omitempty"`
}

func (s SystemsV1BundleDistributionS3Config) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SystemsV1BundleDistributionS3Config) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SystemsV1BundleDistributionS3Config) GetAccessKeys() *string {
	if o == nil {
		return nil
	}
	return o.AccessKeys
}

func (o *SystemsV1BundleDistributionS3Config) GetBucket() string {
	if o == nil {
		return ""
	}
	return o.Bucket
}

func (o *SystemsV1BundleDistributionS3Config) GetContextPath() *string {
	if o == nil {
		return nil
	}
	return o.ContextPath
}

func (o *SystemsV1BundleDistributionS3Config) GetDiscoveryPath() *string {
	if o == nil {
		return nil
	}
	return o.DiscoveryPath
}

func (o *SystemsV1BundleDistributionS3Config) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *SystemsV1BundleDistributionS3Config) GetOpaCredentials() *SystemsV1BundleDistributionS3ConfigOpaCredentials {
	if o == nil {
		return nil
	}
	return o.OpaCredentials
}

func (o *SystemsV1BundleDistributionS3Config) GetPolicyPath() *string {
	if o == nil {
		return nil
	}
	return o.PolicyPath
}

func (o *SystemsV1BundleDistributionS3Config) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *SystemsV1BundleDistributionS3Config) GetRoleArn() *string {
	if o == nil {
		return nil
	}
	return o.RoleArn
}
