// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/internal/utils"
)

type SystemsV1ColumnMapping struct {
	// column key (also the search key)
	Key string `json:"key"`
	// dot-separated decision property path
	Path string `json:"path"`
	// column type: one of "string", "boolean", "date", "integer", "float"
	Type *string `default:"string" json:"type"`
}

func (s SystemsV1ColumnMapping) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SystemsV1ColumnMapping) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SystemsV1ColumnMapping) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *SystemsV1ColumnMapping) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *SystemsV1ColumnMapping) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
