// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/internal/utils"
)

// Discovery - discovery config settings for OPAs linked to the system. (in case of conflict with system-type defined setting, this value takes precedence)
type Discovery struct {
}

// Extra - extra deployment settings
type Extra struct {
}

type SystemsV1SystemDeploymentParameters struct {
	// true to fail close
	DenyOnOpaFail *bool `default:"false" json:"deny_on_opa_fail"`
	// discovery config settings for OPAs linked to the system. (in case of conflict with system-type defined setting, this value takes precedence)
	Discovery *Discovery `json:"discovery,omitempty"`
	// extra deployment settings
	Extra *Extra `json:"extra,omitempty"`
	// HTTP proxy URL
	HTTPProxy *string `json:"http_proxy,omitempty"`
	// HTTPS proxy URL
	HTTPSProxy *string `json:"https_proxy,omitempty"`
	// minimum Kubernetes version expected (where applicable)
	KubernetesVersion *string `json:"kubernetes_version,omitempty"`
	// Custom name for mutating webhook (useful for changing webhook order of execution)
	MutatingWebhookName *string `json:"mutating_webhook_name,omitempty"`
	// Kubernetes namespace the system is deployed to
	Namespace *string `json:"namespace,omitempty"`
	// URLs that should be excluded from proxying
	NoProxy *string `json:"no_proxy,omitempty"`
	// Kubernetes webhook timeout (where applicable)
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`
	// trusted CA certificates
	TrustedCaCerts []string `json:"trusted_ca_certs,omitempty"`
	// trusted container registry
	TrustedContainerRegistry *string `json:"trusted_container_registry,omitempty"`
}

func (s SystemsV1SystemDeploymentParameters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SystemsV1SystemDeploymentParameters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SystemsV1SystemDeploymentParameters) GetDenyOnOpaFail() *bool {
	if o == nil {
		return nil
	}
	return o.DenyOnOpaFail
}

func (o *SystemsV1SystemDeploymentParameters) GetDiscovery() *Discovery {
	if o == nil {
		return nil
	}
	return o.Discovery
}

func (o *SystemsV1SystemDeploymentParameters) GetExtra() *Extra {
	if o == nil {
		return nil
	}
	return o.Extra
}

func (o *SystemsV1SystemDeploymentParameters) GetHTTPProxy() *string {
	if o == nil {
		return nil
	}
	return o.HTTPProxy
}

func (o *SystemsV1SystemDeploymentParameters) GetHTTPSProxy() *string {
	if o == nil {
		return nil
	}
	return o.HTTPSProxy
}

func (o *SystemsV1SystemDeploymentParameters) GetKubernetesVersion() *string {
	if o == nil {
		return nil
	}
	return o.KubernetesVersion
}

func (o *SystemsV1SystemDeploymentParameters) GetMutatingWebhookName() *string {
	if o == nil {
		return nil
	}
	return o.MutatingWebhookName
}

func (o *SystemsV1SystemDeploymentParameters) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *SystemsV1SystemDeploymentParameters) GetNoProxy() *string {
	if o == nil {
		return nil
	}
	return o.NoProxy
}

func (o *SystemsV1SystemDeploymentParameters) GetTimeoutSeconds() *int {
	if o == nil {
		return nil
	}
	return o.TimeoutSeconds
}

func (o *SystemsV1SystemDeploymentParameters) GetTrustedCaCerts() []string {
	if o == nil {
		return nil
	}
	return o.TrustedCaCerts
}

func (o *SystemsV1SystemDeploymentParameters) GetTrustedContainerRegistry() *string {
	if o == nil {
		return nil
	}
	return o.TrustedContainerRegistry
}
