// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SystemsV1PolicyConfig struct {
	// policy on when to (re)generate the policy
	Created     *string                    `json:"created,omitempty"`
	Enforcement SystemsV1EnforcementConfig `json:"enforcement"`
	// policy ID (path)
	ID string `json:"id"`
	// rego modules policy consists of
	Modules []SystemsV1Module     `json:"modules,omitempty"`
	Rules   *PoliciesV1RuleCounts `json:"rules,omitempty"`
	// policy type e.g. validating/rules
	Type string `json:"type"`
}

func (o *SystemsV1PolicyConfig) GetCreated() *string {
	if o == nil {
		return nil
	}
	return o.Created
}

func (o *SystemsV1PolicyConfig) GetEnforcement() SystemsV1EnforcementConfig {
	if o == nil {
		return SystemsV1EnforcementConfig{}
	}
	return o.Enforcement
}

func (o *SystemsV1PolicyConfig) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SystemsV1PolicyConfig) GetModules() []SystemsV1Module {
	if o == nil {
		return nil
	}
	return o.Modules
}

func (o *SystemsV1PolicyConfig) GetRules() *PoliciesV1RuleCounts {
	if o == nil {
		return nil
	}
	return o.Rules
}

func (o *SystemsV1PolicyConfig) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
