// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SystemsV1DatasourceConfig struct {
	// datasource category
	Category string `json:"category"`
	// datasource ID
	ID string `json:"id"`
	// optional datasources can be deleted without being recreated automatically
	Optional *bool         `json:"optional,omitempty"`
	Status   *MetaV1Status `json:"status,omitempty"`
}

func (o *SystemsV1DatasourceConfig) GetCategory() string {
	if o == nil {
		return ""
	}
	return o.Category
}

func (o *SystemsV1DatasourceConfig) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SystemsV1DatasourceConfig) GetOptional() *bool {
	if o == nil {
		return nil
	}
	return o.Optional
}

func (o *SystemsV1DatasourceConfig) GetStatus() *MetaV1Status {
	if o == nil {
		return nil
	}
	return o.Status
}
