// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SystemsV1GcpMetadataAuthPlugin struct {
	// the access token metadata path to use
	AccessTokenPath string `json:"access_token_path"`
	// the audience to use when fetching identity tokens
	Audience string `json:"audience"`
	// the metadata endpoint to use
	Endpoint string `json:"endpoint"`
	// the identity token metadata path to use
	IDTokenPath string `json:"id_token_path"`
	// the set of scopes to use when fetching access token
	Scopes []string `json:"scopes"`
}

func (o *SystemsV1GcpMetadataAuthPlugin) GetAccessTokenPath() string {
	if o == nil {
		return ""
	}
	return o.AccessTokenPath
}

func (o *SystemsV1GcpMetadataAuthPlugin) GetAudience() string {
	if o == nil {
		return ""
	}
	return o.Audience
}

func (o *SystemsV1GcpMetadataAuthPlugin) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *SystemsV1GcpMetadataAuthPlugin) GetIDTokenPath() string {
	if o == nil {
		return ""
	}
	return o.IDTokenPath
}

func (o *SystemsV1GcpMetadataAuthPlugin) GetScopes() []string {
	if o == nil {
		return []string{}
	}
	return o.Scopes
}
