// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type SystemsV1BundleDistributionS3ConfigOpaCredentials struct {
	EnvironmentCredentials *SystemsV1BundleDistributionS3ConfigOpaCredentialsEnvironmentCredentials `json:"environment_credentials,omitempty"`
	MetadataCredentials    *SystemsV1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials    `json:"metadata_credentials,omitempty"`
	WebIdentityCredentials *SystemsV1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials `json:"web_identity_credentials,omitempty"`
}

func (o *SystemsV1BundleDistributionS3ConfigOpaCredentials) GetEnvironmentCredentials() *SystemsV1BundleDistributionS3ConfigOpaCredentialsEnvironmentCredentials {
	if o == nil {
		return nil
	}
	return o.EnvironmentCredentials
}

func (o *SystemsV1BundleDistributionS3ConfigOpaCredentials) GetMetadataCredentials() *SystemsV1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials {
	if o == nil {
		return nil
	}
	return o.MetadataCredentials
}

func (o *SystemsV1BundleDistributionS3ConfigOpaCredentials) GetWebIdentityCredentials() *SystemsV1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials {
	if o == nil {
		return nil
	}
	return o.WebIdentityCredentials
}
