// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type SystemsV1BearerAuthPlugin struct {
	// bearer token scheme to specify
	Scheme *string `json:"scheme,omitempty"`
	// enables token-based authentication and supplies the bearer token to authenticate with
	Token string `json:"token"`
	// enables token-based authentication and supplies the path to the bearer token to authenticate with
	TokenPath string `json:"token_path"`
}

func (o *SystemsV1BearerAuthPlugin) GetScheme() *string {
	if o == nil {
		return nil
	}
	return o.Scheme
}

func (o *SystemsV1BearerAuthPlugin) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *SystemsV1BearerAuthPlugin) GetTokenPath() string {
	if o == nil {
		return ""
	}
	return o.TokenPath
}
