// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SystemsV1AwsWebIdentityCredentialService struct {
	// the AWS region to use for the sts regional endpoint (default: global)
	AwsRegion string `json:"aws_region"`
	// the session name used to identify the assumed role session (default: open-policy-agent)
	SessionName string `json:"session_name"`
}

func (o *SystemsV1AwsWebIdentityCredentialService) GetAwsRegion() string {
	if o == nil {
		return ""
	}
	return o.AwsRegion
}

func (o *SystemsV1AwsWebIdentityCredentialService) GetSessionName() string {
	if o == nil {
		return ""
	}
	return o.SessionName
}
