// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SystemsV1SystemsPutResponse struct {
	RequestID *string               `json:"request_id,omitempty"`
	Result    SystemsV1SystemConfig `json:"result"`
}

func (o *SystemsV1SystemsPutResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *SystemsV1SystemsPutResponse) GetResult() SystemsV1SystemConfig {
	if o == nil {
		return SystemsV1SystemConfig{}
	}
	return o.Result
}
