// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SystemsV1RuleDecisionMappings struct {
	Allowed *SystemsV1AllowedMapping `json:"allowed,omitempty"`
	// decision mappings for additional columns
	Columns []SystemsV1ColumnMapping `json:"columns,omitempty"`
	Reason  *SystemsV1ReasonMapping  `json:"reason,omitempty"`
}

func (o *SystemsV1RuleDecisionMappings) GetAllowed() *SystemsV1AllowedMapping {
	if o == nil {
		return nil
	}
	return o.Allowed
}

func (o *SystemsV1RuleDecisionMappings) GetColumns() []SystemsV1ColumnMapping {
	if o == nil {
		return nil
	}
	return o.Columns
}

func (o *SystemsV1RuleDecisionMappings) GetReason() *SystemsV1ReasonMapping {
	if o == nil {
		return nil
	}
	return o.Reason
}
