// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

type SystemsV1AwsMetadataCredentialService struct {
	// the AWS region to use for the AWS signing service credential method
	AwsRegion string `json:"aws_region"`
	// the IAM role to use for the AWS signing service credential method
	IamRole *string `json:"iam_role,omitempty"`
}

func (o *SystemsV1AwsMetadataCredentialService) GetAwsRegion() string {
	if o == nil {
		return ""
	}
	return o.AwsRegion
}

func (o *SystemsV1AwsMetadataCredentialService) GetIamRole() *string {
	if o == nil {
		return nil
	}
	return o.IamRole
}
