// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SystemsV1SystemsPostResponse struct {
	RequestID *string               `json:"request_id,omitempty"`
	Result    SystemsV1SystemConfig `json:"result"`
}

func (o *SystemsV1SystemsPostResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *SystemsV1SystemsPostResponse) GetResult() SystemsV1SystemConfig {
	if o == nil {
		return SystemsV1SystemConfig{}
	}
	return o.Result
}
