// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

import (
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/internal/utils"
)

type SystemsV1Module struct {
	// module name
	Name string `json:"name"`
	// module is a placeholder
	Placeholder *bool `default:"false" json:"placeholder"`
	// true if module is read-only
	ReadOnly bool                  `json:"read_only"`
	Rules    *PoliciesV1RuleCounts `json:"rules,omitempty"`
}

func (s SystemsV1Module) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SystemsV1Module) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SystemsV1Module) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SystemsV1Module) GetPlaceholder() *bool {
	if o == nil {
		return nil
	}
	return o.Placeholder
}

func (o *SystemsV1Module) GetReadOnly() bool {
	if o == nil {
		return false
	}
	return o.ReadOnly
}

func (o *SystemsV1Module) GetRules() *PoliciesV1RuleCounts {
	if o == nil {
		return nil
	}
	return o.Rules
}
