// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/Styra/terraform-provider-styra/internal/sdk/internal/utils"
	"time"
)

type SystemsV1MigrationRecord struct {
	From           string    `json:"from"`
	InitiatedBy    string    `json:"initiated_by"`
	InitiatingUser string    `json:"initiating_user"`
	MigratedAt     time.Time `json:"migrated_at"`
	Recovered      *bool     `json:"recovered,omitempty"`
	To             string    `json:"to"`
}

func (s SystemsV1MigrationRecord) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SystemsV1MigrationRecord) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SystemsV1MigrationRecord) GetFrom() string {
	if o == nil {
		return ""
	}
	return o.From
}

func (o *SystemsV1MigrationRecord) GetInitiatedBy() string {
	if o == nil {
		return ""
	}
	return o.InitiatedBy
}

func (o *SystemsV1MigrationRecord) GetInitiatingUser() string {
	if o == nil {
		return ""
	}
	return o.InitiatingUser
}

func (o *SystemsV1MigrationRecord) GetMigratedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.MigratedAt
}

func (o *SystemsV1MigrationRecord) GetRecovered() *bool {
	if o == nil {
		return nil
	}
	return o.Recovered
}

func (o *SystemsV1MigrationRecord) GetTo() string {
	if o == nil {
		return ""
	}
	return o.To
}
