// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/Styra/terraform-provider-styra/internal/sdk"
	"github.com/Styra/terraform-provider-styra/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &PolicyDataSource{}
var _ datasource.DataSourceWithConfigure = &PolicyDataSource{}

func NewPolicyDataSource() datasource.DataSource {
	return &PolicyDataSource{}
}

// PolicyDataSource is the data source implementation.
type PolicyDataSource struct {
	client *sdk.StyraDas
}

// PolicyDataSourceModel describes the data model.
type PolicyDataSourceModel struct {
	Dependencies types.Bool   `tfsdk:"dependencies"`
	Policy       types.String `tfsdk:"policy"`
	RequestID    types.String `tfsdk:"request_id"`
	Result       types.String `tfsdk:"result"`
}

// Metadata returns the data source type name.
func (r *PolicyDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_policy"
}

// Schema defines the schema for the data source.
func (r *PolicyDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Policy DataSource",

		Attributes: map[string]schema.Attribute{
			"dependencies": schema.BoolAttribute{
				Optional:    true,
				Description: `include dependencies`,
			},
			"policy": schema.StringAttribute{
				Required:    true,
				Description: `policy name`,
			},
			"request_id": schema.StringAttribute{
				Computed: true,
			},
			"result": schema.StringAttribute{
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
		},
	}
}

func (r *PolicyDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.StyraDas)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.StyraDas, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *PolicyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *PolicyDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	policy := data.Policy.ValueString()
	dependencies := new(bool)
	if !data.Dependencies.IsUnknown() && !data.Dependencies.IsNull() {
		*dependencies = data.Dependencies.ValueBool()
	} else {
		dependencies = nil
	}
	request := operations.GetPolicyRequest{
		Policy:       policy,
		Dependencies: dependencies,
	}
	res, err := r.client.Policies.GetPolicy(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.PoliciesV1PolicyGetResponse == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedPoliciesV1PolicyGetResponse(res.PoliciesV1PolicyGetResponse)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
