// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/StyraInc/terraform-provider-styra/internal/sdk"
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"net/http"
)

var _ provider.Provider = &StyraProvider{}

type StyraProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// StyraProviderModel describes the provider data model.
type StyraProviderModel struct {
	ServerURL types.String `tfsdk:"server_url"`
	Bearer    types.String `tfsdk:"bearer"`
}

func (p *StyraProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "styra"
	resp.Version = p.version
}

func (p *StyraProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: `Styra API: Styra DAS is entirely API-driven.` + "\n" +
			`` + "\n" +
			`Access to the APIs requires authentication that should be provided as an Authorization HTTP header including a Styra DAS-issued token:` + "\n" +
			`` + "\n" +
			`` + "`" + `Authorization: Bearer <YOURTOKENHERE>` + "`" + `` + "\n" +
			`` + "\n" +
			`To request a token you need to have an Styra account, and create a token via the API Tokens menu.`,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://TENANT.styra.com/)",
				Optional:            true,
				Required:            false,
			},
			"bearer": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
		},
	}
}

func (p *StyraProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data StyraProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://TENANT.styra.com/"
	}

	bearer := data.Bearer.ValueString()
	security := shared.Security{
		Bearer: bearer,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
		sdk.WithClient(http.DefaultClient),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *StyraProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewLibraryResource,
		NewPolicyResource,
		NewSecretResource,
		NewStackResource,
		NewSystemResource,
	}
}

func (p *StyraProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewLibraryDataSource,
		NewPolicyDataSource,
		NewSecretDataSource,
		NewStackDataSource,
		NewSystemDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &StyraProvider{
			version: version,
		}
	}
}
