// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/StyraInc/terraform-provider-styra/internal/provider/types"
	"github.com/StyraInc/terraform-provider-styra/internal/sdk"
	"github.com/StyraInc/terraform-provider-styra/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &RoleBindingDataSource{}
var _ datasource.DataSourceWithConfigure = &RoleBindingDataSource{}

func NewRoleBindingDataSource() datasource.DataSource {
	return &RoleBindingDataSource{}
}

// RoleBindingDataSource is the data source implementation.
type RoleBindingDataSource struct {
	client *sdk.StyraDas
}

// RoleBindingDataSourceModel describes the data model.
type RoleBindingDataSourceModel struct {
	ID             types.String                  `tfsdk:"id"`
	Metadata       tfTypes.MetaV2ObjectMeta      `tfsdk:"metadata"`
	RequestID      types.String                  `tfsdk:"request_id"`
	ResourceFilter tfTypes.AuthzV2ResourceFilter `tfsdk:"resource_filter"`
	RoleID         types.String                  `tfsdk:"role_id"`
	Subjects       []tfTypes.AuthzV2Subject      `tfsdk:"subjects"`
}

// Metadata returns the data source type name.
func (r *RoleBindingDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_role_binding"
}

// Schema defines the schema for the data source.
func (r *RoleBindingDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "RoleBinding DataSource",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:    true,
				Description: `rolebinding ID`,
			},
			"metadata": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Computed: true,
					},
					"created_by": schema.StringAttribute{
						Computed: true,
					},
					"created_through": schema.StringAttribute{
						Computed: true,
					},
					"last_modified_at": schema.StringAttribute{
						Computed: true,
					},
					"last_modified_by": schema.StringAttribute{
						Computed: true,
					},
					"last_modified_through": schema.StringAttribute{
						Computed: true,
					},
				},
			},
			"request_id": schema.StringAttribute{
				Computed: true,
			},
			"resource_filter": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:    true,
						Description: `resource ID e.g., system123`,
					},
					"kind": schema.StringAttribute{
						Computed:    true,
						Description: `resource type e.g., system`,
					},
				},
			},
			"role_id": schema.StringAttribute{
				Computed:    true,
				Description: `role ID e.g., SystemOwner`,
			},
			"subjects": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"claim_config": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"identity_provider": schema.StringAttribute{
									Computed:    true,
									Description: `identity provider ID`,
								},
								"key": schema.StringAttribute{
									Computed:    true,
									Description: `OIDC claim key`,
								},
								"value": schema.StringAttribute{
									Computed:    true,
									Description: `OIDC claim value. Use '*' to specify any value.`,
								},
							},
						},
						"id": schema.StringAttribute{
							Computed:    true,
							Description: `subject ID (not needed for claim subjects)`,
						},
						"kind": schema.StringAttribute{
							Computed:    true,
							Description: `subject type e.g., user`,
						},
					},
				},
				Description: `list of subjects`,
			},
		},
	}
}

func (r *RoleBindingDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.StyraDas)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.StyraDas, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *RoleBindingDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *RoleBindingDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetRoleBindingV2Request{
		ID: id,
	}
	res, err := r.client.Authz.GetRoleBindingV2(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AuthzV2RoleBindingsGetResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedAuthzV2RoleBindingConfig(&res.AuthzV2RoleBindingsGetResponse.Rolebinding)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
