// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AuthzV2ResourceFilter struct {
	ID   types.String `tfsdk:"id"`
	Kind types.String `tfsdk:"kind"`
}
