// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AuthzV2ClaimConfig struct {
	IdentityProvider types.String `tfsdk:"identity_provider"`
	Key              types.String `tfsdk:"key"`
	Value            types.String `tfsdk:"value"`
}
