// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type CryptoSignature struct {
	Excluded   types.String `tfsdk:"excluded"`
	Signatures types.String `tfsdk:"signatures"`
}
