// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GitV1SSHCredentials struct {
	Passphrase types.String `tfsdk:"passphrase"`
	PrivateKey types.String `tfsdk:"private_key"`
}
