// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type GitV1GitRepoConfig struct {
	Commit         types.String         `tfsdk:"commit"`
	Credentials    types.String         `tfsdk:"credentials"`
	Path           types.String         `tfsdk:"path"`
	Reference      types.String         `tfsdk:"reference"`
	SSHCredentials *GitV1SSHCredentials `tfsdk:"ssh_credentials"`
	URL            types.String         `tfsdk:"url"`
}
