// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type LibrariesV1SystemBundle struct {
	BundleID types.String `tfsdk:"bundle_id"`
	Version  types.Int64  `tfsdk:"version"`
}
