// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type LibrariesV1SourceControlConfig struct {
	LibraryOrigin        *GitV1GitRepoConfig `tfsdk:"library_origin"`
	Origin               *GitV1GitRepoConfig `tfsdk:"origin"`
	UseWorkspaceSettings types.Bool          `tfsdk:"use_workspace_settings"`
}
