// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type LibrariesV1LibraryEntityExpanded struct {
	Datasources   []SystemsV1DatasourceConfig     `tfsdk:"datasources"`
	Description   types.String                    `tfsdk:"description"`
	ID            types.String                    `tfsdk:"id"`
	Metadata      *MetaV2ObjectMeta               `tfsdk:"metadata"`
	Policies      []SystemsV1PolicyConfig         `tfsdk:"policies"`
	ReadOnly      types.Bool                      `tfsdk:"read_only"`
	SourceControl *LibrariesV1SourceControlConfig `tfsdk:"source_control"`
	UsedBy        []LibrariesV1SystemUsingLibrary `tfsdk:"used_by"`
}
