// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type LibrariesV1SourceControlConfig struct {
	LibraryOrigin        *GitV1GitRepoConfig `tfsdk:"library_origin"`
	UseWorkspaceSettings types.Bool          `tfsdk:"use_workspace_settings"`
}
