// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type MetaV2ObjectMeta struct {
	CreatedAt           types.String `tfsdk:"created_at"`
	CreatedBy           types.String `tfsdk:"created_by"`
	CreatedThrough      types.String `tfsdk:"created_through"`
	LastModifiedAt      types.String `tfsdk:"last_modified_at"`
	LastModifiedBy      types.String `tfsdk:"last_modified_by"`
	LastModifiedThrough types.String `tfsdk:"last_modified_through"`
}
