// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type StacksV1SourceControlConfig struct {
	StackOrigin          *GitV1GitRepoConfig `tfsdk:"stack_origin"`
	UseWorkspaceSettings types.Bool          `tfsdk:"use_workspace_settings"`
}
