// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1OpaConfigServiceDeclaration struct {
	AllowInsecureTLS             types.Bool                                       `tfsdk:"allow_insecure_tls"`
	Credentials                  *SystemsV1OpaConfigServiceDeclarationCredentials `tfsdk:"credentials"`
	Headers                      map[string]types.String                          `tfsdk:"headers"`
	Keys                         map[string]KeysConfig                            `tfsdk:"keys"`
	Name                         types.String                                     `tfsdk:"name"`
	ResponseHeaderTimeoutSeconds types.Int64                                      `tfsdk:"response_header_timeout_seconds"`
	TLS                          *SystemsV1ServerTLSConfig                        `tfsdk:"tls"`
	Type                         types.String                                     `tfsdk:"type"`
	URL                          types.String                                     `tfsdk:"url"`
}
