// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1AllowedMapping struct {
	Expected types.String `tfsdk:"expected"`
	Negated  types.Bool   `tfsdk:"negated"`
	Path     types.String `tfsdk:"path"`
}
