// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1BearerAuthPlugin struct {
	Scheme    types.String `tfsdk:"scheme"`
	Token     types.String `tfsdk:"token"`
	TokenPath types.String `tfsdk:"token_path"`
}
