// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1SystemDeploymentParameters struct {
	DenyOnOpaFail            types.Bool      `tfsdk:"deny_on_opa_fail"`
	Discovery                *TypeParameters `tfsdk:"discovery"`
	Extra                    *TypeParameters `tfsdk:"extra"`
	HTTPProxy                types.String    `tfsdk:"http_proxy"`
	HTTPSProxy               types.String    `tfsdk:"https_proxy"`
	KubernetesVersion        types.String    `tfsdk:"kubernetes_version"`
	MutatingWebhookName      types.String    `tfsdk:"mutating_webhook_name"`
	Namespace                types.String    `tfsdk:"namespace"`
	NoProxy                  types.String    `tfsdk:"no_proxy"`
	TimeoutSeconds           types.Int64     `tfsdk:"timeout_seconds"`
	TrustedCaCerts           []types.String  `tfsdk:"trusted_ca_certs"`
	TrustedContainerRegistry types.String    `tfsdk:"trusted_container_registry"`
}
