// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1EnforcementConfig struct {
	Enforced types.Bool   `tfsdk:"enforced"`
	Type     types.String `tfsdk:"type"`
}
