// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1BundleDownloadConfig struct {
	DeltaBundles types.Bool `tfsdk:"delta_bundles"`
}
