// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1DatasourceConfig struct {
	Category types.String  `tfsdk:"category"`
	ID       types.String  `tfsdk:"id"`
	Optional types.Bool    `tfsdk:"optional"`
	Status   *MetaV1Status `tfsdk:"status"`
}
