// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

type SystemsV1RuleDecisionMappings struct {
	Allowed *SystemsV1AllowedMapping `tfsdk:"allowed"`
	Columns []SystemsV1ColumnMapping `tfsdk:"columns"`
	Reason  *SystemsV1ReasonMapping  `tfsdk:"reason"`
}
