// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1OpaConfigBundleDeclaration struct {
	Persist        types.Bool                   `tfsdk:"persist"`
	Polling        *SystemsV1PollingConfig      `tfsdk:"polling"`
	Resource       types.String                 `tfsdk:"resource"`
	Service        types.String                 `tfsdk:"service"`
	Signing        *SystemsV1VerificationConfig `tfsdk:"signing"`
	SizeLimitBytes types.Int64                  `tfsdk:"size_limit_bytes"`
}
