// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1V1RoleBindingConfig struct {
	ID       types.String `tfsdk:"id"`
	RoleName types.String `tfsdk:"role_name"`
}
