// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1BundleDistributionS3Config struct {
	AccessKeys     types.String                                       `tfsdk:"access_keys"`
	Bucket         types.String                                       `tfsdk:"bucket"`
	ContextPath    types.String                                       `tfsdk:"context_path"`
	DiscoveryPath  types.String                                       `tfsdk:"discovery_path"`
	Endpoint       types.String                                       `tfsdk:"endpoint"`
	OpaCredentials *SystemsV1BundleDistributionS3ConfigOpaCredentials `tfsdk:"opa_credentials"`
	PolicyPath     types.String                                       `tfsdk:"policy_path"`
	Region         types.String                                       `tfsdk:"region"`
	RoleArn        types.String                                       `tfsdk:"role_arn"`
}
