// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1BundleRegistryConfig struct {
	DisableBundleCompatibilityCheck types.Bool                           `tfsdk:"disable_bundle_compatibility_check"`
	DistributionS3                  *SystemsV1BundleDistributionS3Config `tfsdk:"distribution_s3"`
	Entrypoints                     []types.String                       `tfsdk:"entrypoints"`
	ManualDeployment                types.Bool                           `tfsdk:"manual_deployment"`
	ManualDeploymentOverrides       map[string]types.Bool                `tfsdk:"manual_deployment_overrides"`
	MaxBundles                      types.Int64                          `tfsdk:"max_bundles"`
	MaxDeployedBundles              types.Int64                          `tfsdk:"max_deployed_bundles"`
	OptimizationLevel               types.Int64                          `tfsdk:"optimization_level"`
}
