// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1Module struct {
	Name        types.String          `tfsdk:"name"`
	Placeholder types.Bool            `tfsdk:"placeholder"`
	ReadOnly    types.Bool            `tfsdk:"read_only"`
	Rules       *PoliciesV1RuleCounts `tfsdk:"rules"`
}
