// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1OpaConfigServiceDeclarationCredentials struct {
	AzureManagedIdentity *SystemsV1AzureManagedIdentitiesAuthPlugin  `tfsdk:"azure_managed_identity"`
	Bearer               *SystemsV1BearerAuthPlugin                  `tfsdk:"bearer"`
	ClientTLS            *SystemsV1ClientTLSAuthPlugin               `tfsdk:"client_tls"`
	GcpMetadata          *SystemsV1GcpMetadataAuthPlugin             `tfsdk:"gcp_metadata"`
	Oauth2               *SystemsV1Oauth2ClientCredentialsAuthPlugin `tfsdk:"oauth2"`
	Plugin               types.String                                `tfsdk:"plugin"`
	S3Signing            *SystemsV1AwsSigningAuthPlugin              `tfsdk:"s3_signing"`
}
