// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1AgentErrors struct {
	Errors  []MetaV1Status `tfsdk:"errors"`
	Waiting types.Bool     `tfsdk:"waiting"`
}
