// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1GcpMetadataAuthPlugin struct {
	AccessTokenPath types.String   `tfsdk:"access_token_path"`
	Audience        types.String   `tfsdk:"audience"`
	Endpoint        types.String   `tfsdk:"endpoint"`
	IDTokenPath     types.String   `tfsdk:"id_token_path"`
	Scopes          []types.String `tfsdk:"scopes"`
}
