// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials struct {
	AwsRegion types.String `tfsdk:"aws_region"`
	IamRole   types.String `tfsdk:"iam_role"`
}
