// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1ColumnMapping struct {
	Key  types.String `tfsdk:"key"`
	Path types.String `tfsdk:"path"`
	Type types.String `tfsdk:"type"`
}
