// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials struct {
	AwsRegion   types.String `tfsdk:"aws_region"`
	SessionName types.String `tfsdk:"session_name"`
}
