// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type SystemsV1ExternalBundleConfig struct {
	Bundles  map[string]SystemsV1OpaConfigBundleDeclaration `tfsdk:"bundles"`
	Services []SystemsV1OpaConfigServiceDeclaration         `tfsdk:"services"`
}
