// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1SystemConfig struct {
	Authz                 SystemsV1AuthzConfig                     `tfsdk:"authz"`
	BundleDownload        *SystemsV1BundleDownloadConfig           `tfsdk:"bundle_download"`
	BundleRegistry        *SystemsV1BundleRegistryConfig           `tfsdk:"bundle_registry"`
	ContextBundleDataOnly types.Bool                               `tfsdk:"context_bundle_data_only"`
	ContextBundleRoots    []types.String                           `tfsdk:"context_bundle_roots"`
	Datasources           []SystemsV1DatasourceConfig              `tfsdk:"datasources"`
	DecisionMappings      map[string]SystemsV1RuleDecisionMappings `tfsdk:"decision_mappings"`
	DeploymentParameters  *SystemsV1SystemDeploymentParameters     `tfsdk:"deployment_parameters"`
	Description           types.String                             `tfsdk:"description"`
	ErrorSetting          types.String                             `tfsdk:"error_setting"`
	Errors                map[string]SystemsV1AgentErrors          `tfsdk:"errors"`
	ExternalBundles       *SystemsV1ExternalBundleConfig           `tfsdk:"external_bundles"`
	ExternalID            types.String                             `tfsdk:"external_id"`
	FilterStacks          types.Bool                               `tfsdk:"filter_stacks"`
	ID                    types.String                             `tfsdk:"id"`
	KafkaTopic            types.String                             `tfsdk:"kafka_topic"`
	MatchingStacks        []types.String                           `tfsdk:"matching_stacks"`
	Metadata              MetaV2ObjectMeta                         `tfsdk:"metadata"`
	MigrationHistory      []SystemsV1MigrationRecord               `tfsdk:"migration_history"`
	MinimumOpaVersion     types.String                             `tfsdk:"minimum_opa_version"`
	MockOpaEnabled        types.Bool                               `tfsdk:"mock_opa_enabled"`
	Name                  types.String                             `tfsdk:"name"`
	Policies              []SystemsV1PolicyConfig                  `tfsdk:"policies"`
	ReadOnly              types.Bool                               `tfsdk:"read_only"`
	SourceControl         *GitV1SourceControlConfig                `tfsdk:"source_control"`
	Status                types.String                             `tfsdk:"status"`
	Tokens                []TokensV1Token                          `tfsdk:"tokens"`
	Type                  types.String                             `tfsdk:"type"`
	TypeParameters        *TypeParameters                          `tfsdk:"type_parameters"`
	Uninstall             map[string]types.String                  `tfsdk:"uninstall"`
}
