// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SystemsV1PolicyConfig struct {
	Created     types.String               `tfsdk:"created"`
	Enforcement SystemsV1EnforcementConfig `tfsdk:"enforcement"`
	ID          types.String               `tfsdk:"id"`
	Modules     []SystemsV1Module          `tfsdk:"modules"`
	Rules       *PoliciesV1RuleCounts      `tfsdk:"rules"`
	Type        types.String               `tfsdk:"type"`
}
